apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  name: tcs-demo-cluster-feb-22
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 2
        vmSize: Standard_D2_v2
    dnsPrefix: tcscluster
    identity:
      - type: SystemAssigned
    location: West US 2
    resourceGroupName: Crossplane-demo
    tags:
      Environment: Production